add available room tab
Yuanpei-Intelligence/Underground-System-Yuanpei pull request #16
Opened 2021-08-09 16:22 UTC by mrlazy1708

![截圖 2021-08-10 上午12 21 33](https://user-images.githubusercontent.com/49296495/128739834-eef030c8-b62e-4792-99c8-0f3ceaf6bb74.jpg)
![截圖 2021-08-10 上午12 21 34](https://user-images.githubusercontent.com/49296495/128739812-129b5f8a-067c-487c-b28c-74f2356ecddb.jpg)

2021-08-11 19:26 UTC, YWolfeee commented
几个问题
1、测试一下手机版的效果，然后空闲房间放在左边，这是默认显示的
2、空闲房间的显示不是给他们线上预约的，是提供临时预约的，所以是不能在这儿点击“预约”的。这里最好可以有一个小问号（ask孙英博），告诉大家这个房间显示意味着可以直接到该房间门口刷卡发起临时预约。这个临时预约是有规则地，需要在小问号弹出的提示中写上，规则可以问唐明川
3、房间是否available如果用现在这个呈现方式的话有点信息量太低了，可以考虑更加具体一点的方式，例如并排的一堆按钮/表格，上面写着房间号，用颜色说明是否可以发起临时预约之类的。这个可能需要在设计一下，不过我觉得不需要现在这样的img

2021-08-12 00:48 UTC, mrlazy1708 commented
哦哦 看来是我临时预约理解错了

2021-08-12 17:29 UTC, mrlazy1708 commented
![截圖 2021-08-13 上午1 26 18](https://user-images.githubusercontent.com/49296495/129241715-db41ae56-8d17-48f9-aa91-1ae92f3c3fa1.jpg)
![截圖 2021-08-13 上午1 26 46](https://user-images.githubusercontent.com/49296495/129241725-8274f63b-3f18-4aa4-baf4-14f43bfa973a.jpg)

2021-08-12 17:29 UTC, mrlazy1708 commented
改成了这样行不

2021-08-13 13:24 UTC, mrlazy1708 commented
![截圖 2021-08-13 下午9 23 36](https://user-images.githubusercontent.com/49296495/129363670-a881f394-cd36-4c05-a7dc-8a8814fd024e.jpg)
把右边也变成这样了，加了三种颜色的拥挤程度表示

2021-08-13 13:25 UTC, mrlazy1708 commented
然后左边只有talk_room

2021-08-14 06:32 UTC, mrlazy1708 commented
增加Astart定时函数

2021-08-15 00:40 UTC, YWolfeee commented
感觉挺nice的，你修改结束了不

2021-08-15 06:48 UTC, mrlazy1708 commented
ok任务取消了

2021-08-16 15:22 UTC, mrlazy1708 commented
整理了一下doorcheck，journal统一用operation_writer，暂且把规则设为5min
其实我觉得哪怕1min（59分进去）也没啥关系，只要后面15min没人他就可以刷卡续约

2021-08-16 18:32 UTC, YWolfeee commented on Appointment/utils/web_func.py
> -                                     "因迟到而违约时出现异常: "+tempmessage, "func[finishAppoint]", "Error")
你为什么把这段逻辑删掉了？
如果现在你是到时间自动改成processing的话，那么这两间房就应该自动通过对吧。因为原本是Apointed状态下自动通过。

2021-08-16 18:38 UTC, YWolfeee commented on Appointment/views.py
> +                operation_writer(student, f"房间{Rid}刷卡拒绝：自习室不开放", "func[views::door_check]")
你这个有问题呀，如果这个房间是6:00-1:30(次日)，那就几乎开不了了

2021-08-16 18:50 UTC, YWolfeee commented on Appointment/views.py
> +            stu_appoint = room_appoint.get(students__in=[student])
你这个语法不行啊 `room_appoint`不一定只有一个吧

2021-08-16 19:05 UTC, YWolfeee requested changes

2021-08-16 19:05 UTC, YWolfeee commented on Appointment/views.py
> +                    operation_writer(student, f"房间{Rid}刷卡拒绝：临时预约失败（预约人不合法）", "func[views::door_check]") # TODO: 给个错误提示
哦临时预约成功发起的话提醒在`addAppoint`里面 那你这儿失败的话，你看一下`addAppoint`返回的错误，然后调用`send_wechat_message`吧

2021-08-16 19:05 UTC, YWolfeee commented on Appointment/views.py
> +            if valid and finish - start >= timedelta(minutes=5):    # 时间合法（暂时将间隔定为5min）
你这种怎么能harding coding呢，应该写在json里面读取才好吧

2021-08-16 19:05 UTC, YWolfeee commented on Appointment/views.py
> +                cardcheckinfo_writer(student, room, False, False)
同样加`send_wechat_message`

2021-08-16 19:05 UTC, YWolfeee commented on Appointment/views.py
> -                    assert identity_check(request) is True
为什么把这行删掉？

2021-08-16 19:05 UTC, YWolfeee commented on Appointment/views.py
> +    room_info = [(room, {'Room': room.Rid} in occupied_rooms, format(room_appointments[room.Rid])) for room in talk_room_list]
非常不赞成你写那么长的不加任何注释，你要把每一部分用空行分开，然后解释代码在干什么事情

2021-08-17 01:13 UTC, mrlazy1708 commented on Appointment/utils/web_func.py
> -                                     "因迟到而违约时出现异常: "+tempmessage, "func[finishAppoint]", "Error")
现在就是都不用刷卡，一样到结束时间都改成COMFIRMED

2021-08-17 01:13 UTC, mrlazy1708 commented on Appointment/utils/web_func.py
> -                                     "因迟到而违约时出现异常: "+tempmessage, "func[finishAppoint]", "Error")
现在是都不用刷卡，到结束时间没有违约就改成COMFIRMED

2021-08-17 01:17 UTC, mrlazy1708 commented on Appointment/views.py
> +                operation_writer(student, f"房间{Rid}刷卡拒绝：自习室不开放", "func[views::door_check]")
所以Rfinish在次日情况下的格式是啥？是一个>1d的值吗，那就把d也加上
（这里我没改，就是整理了原先的270col的一行代码

2021-08-17 01:18 UTC, mrlazy1708 commented on Appointment/views.py
> +            stu_appoint = room_appoint.get(students__in=[student])
ok，不过这个student appointment也没用到，只要有就能开门

2021-08-17 01:21 UTC, mrlazy1708 commented on Appointment/views.py
> +                    operation_writer(student, f"房间{Rid}刷卡拒绝：临时预约失败（预约人不合法）", "func[views::door_check]") # TODO: 给个错误提示
utils/utils.py, line345
只要后面是Error就会发，改之前也是这样

2021-08-17 01:22 UTC, mrlazy1708 commented on Appointment/views.py
> +            if valid and finish - start >= timedelta(minutes=5):    # 时间合法（暂时将间隔定为5min）
ok

2021-08-17 01:23 UTC, mrlazy1708 commented on Appointment/views.py
> -                    assert identity_check(request) is True
删错了删错了

2021-08-17 01:24 UTC, mrlazy1708 commented on Appointment/views.py
> +    room_info = [(room, {'Room': room.Rid} in occupied_rooms, format(room_appointments[room.Rid])) for room in talk_room_list]
ok

2021-08-17 05:56 UTC, merged