Change rule of camera check
Yuanpei-Intelligence/Underground-System-Yuanpei pull request #8
Opened 2021-07-14 11:00 UTC by sunyb-dot

2021-07-14 14:01 UTC, YWolfeee requested changes

2021-07-14 14:01 UTC, YWolfeee commented on Appointment/views.py
> -            d = datetime.utcnow()
这一部分的修改没有更新，请pull最新的repo，这样我这里就不会出现你"删掉了其他人的修改的情况"

2021-07-14 15:34 UTC, sunyb-dot commented on Appointment/models.py
> +    Rcheck_status = models.IntegerField('检测状态', default=0)
哦哦，我按照那个方式写一下

2021-07-16 06:01 UTC, YWolfeee commented on Appointment/models.py
> -from Appointment.utils.scheduler_func import cancel_scheduler
这个修改应该加回去

2021-07-16 06:01 UTC, YWolfeee commented on Appointment/views.py
> -import time
这部分不应该去掉

2021-07-16 07:13 UTC, yabukota commented on Appointment/views.py
> -import time
20行也import了一个time，38行这里可以改一下，需要哪个函数就import哪个函数，如import time.mktime

2021-07-16 07:20 UTC, closed without merging